insert into User (USERID, NAME, USERNAME, PASSWORD, SUBSTITUTIONS) values (USER_SEQ.nextval, 'test', 'test', 'abc123', 8);
insert into User (USERID, NAME, USERNAME, PASSWORD, SUBSTITUTIONS) values (USER_SEQ.nextval, 'test2', 'test2', 'abc123', 8);

insert into Cyclist (CYCLISTID, NAME, VALUE) values (CYCLIST_SEQ.nextval, 'cyclist1', 10);
insert into Cyclist (CYCLISTID, NAME, VALUE) values (CYCLIST_SEQ.nextval, 'cyclist2', 10);
insert into Cyclist (CYCLISTID, NAME, VALUE) values (CYCLIST_SEQ.nextval, 'cyclist3', 10);
insert into Cyclist (CYCLISTID, NAME, VALUE) values (CYCLIST_SEQ.nextval, 'cyclist4', 10);
insert into Cyclist (CYCLISTID, NAME, VALUE) values (CYCLIST_SEQ.nextval, 'cyclist5', 10);
insert into Cyclist (CYCLISTID, NAME, VALUE) values (CYCLIST_SEQ.nextval, 'cyclist6', 10);
insert into Cyclist (CYCLISTID, NAME, VALUE) values (CYCLIST_SEQ.nextval, 'cyclist7', 10);
insert into Cyclist (CYCLISTID, NAME, VALUE) values (CYCLIST_SEQ.nextval, 'cyclist8', 10);
insert into Cyclist (CYCLISTID, NAME, VALUE) values (CYCLIST_SEQ.nextval, 'cyclist9', 10);


insert into STAGE (STAGEID) values (STAGE_SEQ.nextval);

insert into USER_CYCLIST (USER_USERID, TEAM_CYCLISTID) values (1,1);
insert into USER_CYCLIST (USER_USERID, TEAM_CYCLISTID) values (1,2);
insert into USER_CYCLIST (USER_USERID, TEAM_CYCLISTID) values (1,3);
insert into USER_CYCLIST (USER_USERID, TEAM_CYCLISTID) values (1,4);
insert into USER_CYCLIST (USER_USERID, TEAM_CYCLISTID) values (1,5);
insert into USER_CYCLIST (USER_USERID, TEAM_CYCLISTID) values (1,6);
insert into USER_CYCLIST (USER_USERID, TEAM_CYCLISTID) values (1,7);
insert into USER_CYCLIST (USER_USERID, TEAM_CYCLISTID) values (1,8);

insert into STAGEPOINTS (STAGEPOINTSID, STAGERANK, SPRINTPOINTS, MOUNTAINPOINTS, GCRANK, POINTSRANK, MOUNTAINSRANK, MOSTCOMBATIVE, STAGEID) values (STAGEPOINTS_SEQ.nextval, 1, 1, 1, 1, 1, 1, TRUE, 1);
insert into STAGEPOINTS (STAGEPOINTSID, STAGERANK, SPRINTPOINTS, MOUNTAINPOINTS, GCRANK, POINTSRANK, MOUNTAINSRANK, MOSTCOMBATIVE, STAGEID) values (STAGEPOINTS_SEQ.nextval, 2, 1, 1, 1, 1, 1, TRUE, 1);
insert into STAGEPOINTS (STAGEPOINTSID, STAGERANK, SPRINTPOINTS, MOUNTAINPOINTS, GCRANK, POINTSRANK, MOUNTAINSRANK, MOSTCOMBATIVE, STAGEID) values (STAGEPOINTS_SEQ.nextval, 3, 1, 1, 1, 1, 1, TRUE, 1);
insert into STAGEPOINTS (STAGEPOINTSID, STAGERANK, SPRINTPOINTS, MOUNTAINPOINTS, GCRANK, POINTSRANK, MOUNTAINSRANK, MOSTCOMBATIVE, STAGEID) values (STAGEPOINTS_SEQ.nextval, 4, 1, 1, 1, 1, 1, TRUE, 1);
insert into STAGEPOINTS (STAGEPOINTSID, STAGERANK, SPRINTPOINTS, MOUNTAINPOINTS, GCRANK, POINTSRANK, MOUNTAINSRANK, MOSTCOMBATIVE, STAGEID) values (STAGEPOINTS_SEQ.nextval, 5, 1, 1, 1, 1, 1, TRUE, 1);
insert into STAGEPOINTS (STAGEPOINTSID, STAGERANK, SPRINTPOINTS, MOUNTAINPOINTS, GCRANK, POINTSRANK, MOUNTAINSRANK, MOSTCOMBATIVE, STAGEID) values (STAGEPOINTS_SEQ.nextval, 6, 1, 1, 1, 1, 1, TRUE, 1);
insert into STAGEPOINTS (STAGEPOINTSID, STAGERANK, SPRINTPOINTS, MOUNTAINPOINTS, GCRANK, POINTSRANK, MOUNTAINSRANK, MOSTCOMBATIVE, STAGEID) values (STAGEPOINTS_SEQ.nextval, 7, 1, 1, 1, 1, 1, TRUE, 1);
insert into STAGEPOINTS (STAGEPOINTSID, STAGERANK, SPRINTPOINTS, MOUNTAINPOINTS, GCRANK, POINTSRANK, MOUNTAINSRANK, MOSTCOMBATIVE, STAGEID) values (STAGEPOINTS_SEQ.nextval, 8, 1, 1, 1, 1, 1, TRUE, 1);

insert into CYCLIST_STAGERESULTS (CYCLIST_CYCLISTID, STAGERESULTS_STAGEPOINTSID) values (1, 1);
insert into CYCLIST_STAGERESULTS (CYCLIST_CYCLISTID, STAGERESULTS_STAGEPOINTSID) values (2, 2);
insert into CYCLIST_STAGERESULTS (CYCLIST_CYCLISTID, STAGERESULTS_STAGEPOINTSID) values (3, 3);
insert into CYCLIST_STAGERESULTS (CYCLIST_CYCLISTID, STAGERESULTS_STAGEPOINTSID) values (4, 4);
insert into CYCLIST_STAGERESULTS (CYCLIST_CYCLISTID, STAGERESULTS_STAGEPOINTSID) values (5, 5);
insert into CYCLIST_STAGERESULTS (CYCLIST_CYCLISTID, STAGERESULTS_STAGEPOINTSID) values (6, 6);
insert into CYCLIST_STAGERESULTS (CYCLIST_CYCLISTID, STAGERESULTS_STAGEPOINTSID) values (7, 7);
insert into CYCLIST_STAGERESULTS (CYCLIST_CYCLISTID, STAGERESULTS_STAGEPOINTSID) values (8, 8);

insert into USER_STAGEPOINTS (USER_USERID, STAGEPOINTSLIST_STAGEPOINTSID) VALUES (1,1);
insert into USER_STAGEPOINTS (USER_USERID, STAGEPOINTSLIST_STAGEPOINTSID) VALUES (1,2);
insert into USER_STAGEPOINTS (USER_USERID, STAGEPOINTSLIST_STAGEPOINTSID) VALUES (1,3);
insert into USER_STAGEPOINTS (USER_USERID, STAGEPOINTSLIST_STAGEPOINTSID) VALUES (1,4);
insert into USER_STAGEPOINTS (USER_USERID, STAGEPOINTSLIST_STAGEPOINTSID) VALUES (1,5);
insert into USER_STAGEPOINTS (USER_USERID, STAGEPOINTSLIST_STAGEPOINTSID) VALUES (1,6);
insert into USER_STAGEPOINTS (USER_USERID, STAGEPOINTSLIST_STAGEPOINTSID) VALUES (1,7);
insert into USER_STAGEPOINTS (USER_USERID, STAGEPOINTSLIST_STAGEPOINTSID) VALUES (1,8);


